### ISSUE TITLE
Update download page to match the latest release 

### ISSUE THREAD

**Issue by mxiamxia** [aws-otel/aws-otel.github.io#10]
The download page on our developer portal is outdated. should be updated to match the latest release.
https://aws-otel.github.io/download

**Comment by wilguo** [comment]
Hi Min, do you have the following information I can use to update the downloads portal?
* Release date for the release
* Download artifact Link
* Release Notes Link
* Documentation for the release Link

**Comment by wilguo** [comment]
This issue is solved with this PR, https://github.com/aws-otel/aws-otel.github.io/pull/40.

**Comment by wilguo** [comment]
Closing this issue because changes are reflected in https://github.com/aws-otel/aws-otel.github.io/pull/43.
