### ISSUE TITLE
Add ODFE DataPrepper OTLP support docs to ADOT

### ISSUE THREAD

**Issue by alolita** [aws-otel/aws-otel.github.io#100]
Add OpenTelemetry Collector OTLP support documentation to the section on ADOT OTLP supported components. For example update https://aws-otel.github.io/docs/components/otlp-exporter

https://github.com/opendistro-for-elasticsearch/data-prepper
https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/docs/readme/trace_setup.md

@kowshikn @wrijeff can you file a PR?

**Comment by wrijeff** [comment]
Sure @alolita, will take this one

**Comment by alolita** [comment]
Thanks @wrijeff

**Comment by alolita** [comment]
Ping @wrijeff can you give me a ETA?

**Comment by wrijeff** [comment]
@alolita - should be able to get to this next week, 05/21 at the latest

**Comment by alolita** [comment]
Done.
