### ISSUE TITLE
Broken link in EKS documentation

### ISSUE THREAD

**Issue by hossain-rayhan** [aws-otel/aws-otel.github.io#111]
In EKS deployment [documentation](https://aws-otel.github.io/docs/setup/eks#deploy-aws-otel-collector-on-amazon-eks-as-sidecar), the step 3 (Deploy the application) link is broken. 

In step 3, we have the following deployment command but the link returns 404 Not found!
`kubectl apply -f https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/examples/eks/eks-sidecar.yaml`

**Comment by alolita** [comment]
@hossain-rayhan can you submit a PR?

**Comment by hossain-rayhan** [comment]
will do that. @alolita

**Comment by alolita** [comment]
Ping @hossain-rayhan - can you file a PR for the correction?

**Comment by hossain-rayhan** [comment]
Hi @alolita , I think the file was updated and it works now. Closing this issue.
