### ISSUE TITLE
Would like to enhance docs with images

### ISSUE THREAD

**Issue by jkowall** [aws-otel/aws-otel.github.io#123]
I would like to add some images to one of the documentation pages to make it more clear. Where do you want the images uploaded to in the folder structure? Should I create a vendor-specific subcategory under the /docs/partners/logzio_static or do you prefer them somewhere else?

Thanks!

**Comment by jkowall** [comment]
@alolita Can you please assist with this question? thanks!

**Comment by alolita** [comment]
Hi @jkowall best to add the images under https://github.com/aws-otel/aws-otel.github.io/tree/main/src/assets/img 

Please prefix w "logzio" (<vendorname>) and add to the folder.
