### ISSUE TITLE
Create a new "Component" section at the navigation menu on the left

### ISSUE THREAD

**Issue by mxiamxia** [aws-otel/aws-otel.github.io#14]
We propose to create a Component section on the left navigation menu bar 

Component
* Receiver
  - ECS Container Metrics Receiver
  - Xray Receiver

**Comment by wilguo** [comment]
Hi Min, I have changed the side navigation to include a "Components" section with the 2 pages underneath it. Could you please take a look at the updated side nav (https://aws-otel.github.io/docs/introduction) and let me know if there's anything that needs to be changed. If not, I will close this issue.

**Comment by mxiamxia** [comment]
Looks good. Thank you.
