### ISSUE TITLE
Update Blog Posts Section 

### ISSUE THREAD

**Issue by alolita** [aws-otel/aws-otel.github.io#158]
Update https://aws.amazon.com/blogs/opensource/aws-distro-for-opentelemetry-adds-lambda-layers-for-more-languages-and-collector/ to make it current with the blogs published for AWS Distro for OpenTelemetry on the AWS Open Source blog.

See current list at:
https://aws.amazon.com/blogs/opensource/category/management-tools/aws-distro-for-opentelemetry/

**Comment by alolita** [comment]
@JamesJHPark can you work on this - thx!

**Comment by JamesJHPark** [comment]
Resolved the issue with #165
