### ISSUE TITLE
Update Downloads page to include ADOT public ECR link for downloading images

### ISSUE THREAD

**Issue by alolita** [aws-otel/aws-otel.github.io#159]
Update downloads page at https://aws-otel.github.io/download to include ADOT public ECR link to the website for easy access to downloading Docker images.

ADOT Collector
https://gallery.ecr.aws/aws-observability/aws-otel-collector

ADOT Operator
https://gallery.ecr.aws/aws-observability/aws-otel-operator

**Comment by alolita** [comment]
@JamesJHPark - can you work on this - thx.

**Comment by JamesJHPark** [comment]
Resolved the issue with PR #170
