### ISSUE TITLE
update https://aws-otel.github.io/docs/getting-started/aws-xray page

### ISSUE THREAD

**Issue by mxiamxia** [aws-otel/aws-otel.github.io#16]
Update https://aws-otel.github.io/docs/getting-started/aws-xray page with the guide how to config xray with the collector

**Comment by wilguo** [comment]
@mxiamxia is this issue resolved with PR https://github.com/aws-otel/aws-otel.github.io/pull/17?

**Comment by mxiamxia** [comment]
Yes. closed the issue. Thanks.
