### ISSUE TITLE
Update Know Your Data section on nav bar

### ISSUE THREAD

**Issue by alolita** [aws-otel/aws-otel.github.io#164]
Update link for Traces - link to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#tracing-signal

Update link for Metrics - link to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#metric-signal

Add link for Logs - link to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#log-signal

**Comment by alolita** [comment]
@JamesJHPark - assigning to you.

**Comment by JamesJHPark** [comment]
Resolved the issue with PR #166
