### ISSUE TITLE
Link pointing to internal website

### ISSUE THREAD

**Issue by jdiazcano** [aws-otel/aws-otel.github.io#195]
**What is the link to the page**
https://aws-otel.github.io/docs/setup/docker-images

**What section is the error in**
At the start of `Steps`

**What is the current content being displayed**
There is a link to your corp site that customers do not have access to: https://drive.corp.amazon.com/documents/xiami@/AWS-Observability/docker-compose.yaml

**Proposed content fix**
Something that we have access to (I guess a link to a github file)

**Comment by alolita** [comment]
Fixed.
