### ISSUE TITLE
Add Getting Started with OTLP guide

### ISSUE THREAD

**Issue by alolita** [aws-otel/aws-otel.github.io#27]
Add Getting Started with OTLP guide

References: 
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md
https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/otlphttpexporter/README.md
https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/otlpexporter/README.md

**Comment by wilguo** [comment]
Closing this issue because changes are reflected in https://github.com/aws-otel/aws-otel.github.io/pull/43.
