### ISSUE TITLE
Getting started guide for Sumo Logic

### ISSUE THREAD

**Issue by kesanaps** [aws-otel/aws-otel.github.io#41]
** Component Name **
Description (3-4 sentences), involving data type (metrics, traces, both) and value proposition.
Sumo Logic transaction tracing provides cloud-native transactional intelligence for distributed business workflows, by enriching and analyzing traces, logs, and metrics in real-time with automated generated application topology. All telemetry signals are fully integrated to provide a seamless end-to-end experience during the process of managing and responding to production incidents and to reduce downtime by streamlining root cause analysis.

** Requirements **
State any underlying dependencies and runtime requirements of your component.

Sumo Logic tracing supports the OpenTelemetry standard as well as other legacy open standards and libraries for tracing (e.g. OpenTracing, OpenCensus, Jaeger, Zipkin) and leverages open source componentry from the Cloud Native Computing Foundation (CNCF) to collect distributed tracing data.
Sumo Logic OpenTelemetry supports  all major runtimes such as .NET,Go,Javascript,Java,Python and Ruby.

** Configuration **
Configuration instructions should be both informative and short. For each step in the process, describe what to do and why. If you vend any upstream components, explicitly show how to download/install and configure, with code snippets. Include any and all configuration options, flags or code snippets to modify the component behaviour.

.Net OpenTelemetry auto-instrumentation:
https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Instrument_your_application_with_OpenTelemetry/.NET_OpenTelemetry_auto-instrumentation

Go OpenTelemetry auto-instrumentation:
https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Instrument_your_application_with_OpenTelemetry/Go_OpenTelemetry_auto-instrumentation

Javascript OpenTelemetry auto-instrumentation:
https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Instrument_your_application_with_OpenTelemetry/JavaScript_OpenTelemetry_auto-instrumentation

Java OpenTelemetry auto-instrumentation:
https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Instrument_your_application_with_OpenTelemetry/Java_OpenTelemetry_auto-instrumentation

Python OpenTelemetry auto-instrumentation:
https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Instrument_your_application_with_OpenTelemetry/Python_OpenTelemetry_auto-instrumentation

Ruby OpenTelemetry auto-instrumentation:
https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Instrument_your_application_with_OpenTelemetry/Ruby_OpenTelemetry_auto-instrumentation

** Sample Application **
Link to a sample application hosted on GitHub, if applicable. Sample application instructions should reside in a README.md document, with similar instructions with this format.
N/A

**Comment by KKelvinLo** [comment]
What is your configuration endpoint in the OTLP exporter in the collector config file(YAML)? Can you share a code snippet highlighting the example? Thanks!
