### ISSUE TITLE
Add IAM Role Anywhere instructions to on-prem docs

### ISSUE THREAD

**Issue by mhausenblas** [aws-otel/aws-otel.github.io#429]
In https://aws-otel.github.io/docs/setup/on-premises explain how to use IAM Role Anywhere

**Comment by rafaelpereyra** [comment]
Planned to include:
- References to AWS IAM Roles Anywhere and different options to create a trust anchor
- Requirements for AWS IAM Role trust policy, specifically on the conditions for assume role
- Installation of aws_signing_tool
- AWS SDK Config file changes needed for credential process
- Changes in the environment variables (using .env file) to include credential process

Out of scope:
- Configuration of pki (even using AWS Private Certificate Authority, this will be covered on an AWS Blog post)
- Certificate generation for the aoc user.
