### ISSUE TITLE
ECS Setup doc for SSM parameter doesn't work

### ISSUE THREAD

**Issue by hossain-rayhan** [aws-otel/aws-otel.github.io#45]
**Describe the bug**
While following this [doc](https://aws-otel.github.io/docs/setup/ecs/config-through-ssm#2-create-ssm-parameter) to setup AOC, it throws an error in the `2. Create SSM Parameter` step. 

Error:
```
https://aws-otel.github.io/docs/setup/ecs/config-through-ssm#2-create-ssm-parameter
```

**Steps to reproduce**
Follow the linked doc.

**What did you expect to see?**
No error.

**Proposed solution**
Just use a different name in the doc and test it.

**Comment by JohnWu20** [comment]
Changed the example name:
https://github.com/aws-otel/aws-otel.github.io/pull/46
