### ISSUE TITLE
Building collector as RPM section is out of date

### ISSUE THREAD

**Issue by deki** [aws-otel/aws-otel.github.io#475]
**What is the link to the page**
https://aws-otel.github.io/docs/setup/build-collector-as-rpm

**What section is the error in**
Build Collector as RPM

**What is the current content being displayed**
The page mentions the collector is still BETA.
It uses @mxiamxia personal GitHub repo https://github.com/mxiamxia/aws-opentelemetry-collector which no longer exists.

**Proposed content fix**
For EC2 setup better link to https://aws-otel.github.io/docs/setup/ec2 instead.
For RPM build there is also https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/linux-rpm-demo.md

**Comment by PaurushGarg** [comment]
Closing this issue as the relevant PRs has been merged.
