### ISSUE TITLE
Typo in the name of the company who made the aws-sdk plugin for js (aspect -> aspecto)

### ISSUE THREAD

**Issue by habmic** [aws-otel/aws-otel.github.io#54]
**What is the link to the page**
https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr#tracing-aws-sdk-calls

**What section is the error in**
Tracing AWS SDK Calls

**What is the current content being displayed**
Tracing support to any AWS SDK calls such as Amazon DynamoDB, S3, and etc is provided by the Open Telemetry AWS SDK Instumentation plugin by Aspect IO.

**Proposed content fix**
Tracing support to any AWS SDK calls such as Amazon DynamoDB, S3, and etc is provided by the Open Telemetry AWS SDK Instumentation plugin by [aspecto.io](https://www.aspecto.io/).

There is a typo in the name of the company, it is Aspecto and not Aspect. Would be very nice to include it as a link as well.

**Comment by wilguo** [comment]
Hi @habmic, thanks for letting us know! We will fix that
