### ISSUE TITLE
ADOT logging exporter documentation to use verbosity instead of loglevel

### ISSUE THREAD

**Issue by jayjoshi-git-hub** [aws-otel/aws-otel.github.io#548]
**What is the link to the page**
https://aws-otel.github.io/docs/components/misc-exporters#logging-exporter

**What section is the error in**
Logging Exporter

**What is the current content being displayed**
`````
The following settings are optional:

loglevel (default = info): there are 4 type of settings debug, info, warn, and error. In debug, pipeline data is verbosely logged.
sampling_initial (default = 2): number of messages initially logged each second.
sampling_thereafter (default = 500): sampling rate after the initial messages are logged (every ith message is logged).
``````````

**Proposed content fix**
As loglevel option is deprecated we should update the example and details to start using `verbosity` option

**Comment by Kausik-A** [comment]
The documentation is now updated. Thank you for bringing it to our notice.
