### ISSUE TITLE
Some stale links and other references in AMP/EKS doc

### ISSUE THREAD

**Issue by bellkev** [aws-otel/aws-otel.github.io#628]
**Describe the bug**

A path and a URL in the [Basic Kubernetes/EKS Configuration for AMP](https://aws-otel.github.io/docs/getting-started/prometheus-remote-write-exporter/eks) doc appear incorrect.

**Steps to reproduce**

It seems this directory should be `sample-apps/prometheus-sample-app` instead:
```
cd ./sample-apps/prometheus
```

The link for the k8s DaemonSet YAML config is broken:

This 404s: https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/examples/eks/prometheus-pipeline/eks-prometheus-daemonset.yaml

This appears correct: https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/examples/eks/aws-prometheus/prometheus-daemonset.yaml

**What did you expect to see?**
All of the links and file paths should be correct.

**What did you see instead?**
They are not.

**Environment**
n/a

**Additional context**
n/a

**Comment by rapphil** [comment]
Hi @bellkev 

Thank you for taking the time to write this issue. I really appreciate and we fixed the doc.

Closing the ticket as the issue was solved.
