### ISSUE TITLE
JS documentation is using SimpleSpanProcessor

### ISSUE THREAD

**Issue by anuraaga** [aws-otel/aws-otel.github.io#64]
`SimpleSpanProcessor` should only ever be used with a logging exporter. This needs to be updated to use `BatchSpanProcessor`.

https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr#export-trace-data-to-otlp-exporter

**Comment by alolita** [comment]
@anuraaga can this documentation be improved? @willarmiros have Anuraag's concerns been addressed?

**Comment by willarmiros** [comment]
@alolita See #200. #198 is also a necessary update to JS documentation when you get a chance
