### ISSUE TITLE
Provide an interactive page for select config/doc based on environment

### ISSUE THREAD

**Issue by pingleig** [aws-otel/aws-otel.github.io#99]
There are many ways to run collector on different environments, and it would be good if there is an interactive page that allows user to filter the right config/doc on the website.

One way is to composite a page based on user selection.

```
Seclection:

env: eks
mode: deployment
trace: 
   - otel sdk java
   - xray
metrics:
    - prometheus
    - cloudwatch
awsfeatures:
     - containerinsight

Output:

Example config 

``
exporters:
    awsxray
    awsemf
``

Example manifest

``
k8s yaml
spec:
    xxx
    bla: blabla
``

Copy and paste commands

``
kubectl apply -f xxxxx
kubectl get pods -f 
``

See also (link to related docs)

- otel java sdk get started
- container insight example prometheus workload, jmx, nginx etc.
```

Since we are using gatsby we can write dynamic components and should be to generates shareable urls like `doc?env=eks&exporter=a`

Another (easier) way is have pre defined pages and leads user to the right one based on selection.

```
select your env
- [x] eks
- [ ] ecs

select your metrics
- [ ] n/a
- [x] prometheus
- [x] cadvisor

Output

- setup up prometheus on eks
- setup up cadvisor on eks ... 
```

**Comment by alolita** [comment]
Good suggestions @pingleig We should discuss a list of features that would support such an interactive experience. Having a playground would be great. Perhaps we can extend the playground that Anuraag was working on and integrate with the developer site. Let's discuss.

**Comment by donkee** [comment]
I see this is marked as `completed` - has a page been created to generate a config?

**Comment by pingleig** [comment]
I don't think so, you can try https://github.com/dash0hq/otelbin they can validate config using ADOT and provides a visual interface https://www.otelbin.io/
